TrainingArguments:
  num_train_epochs: 5
  warmup_steps: 500
  per_device_train_batch_size: 4
  weight_decay: 0.01
  logging_steps: 10
  eval_steps: 1000
  save_steps: 999999999
  gradient_accumulation_steps: 1


  