artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/refs/heads/master/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/samsumdata.zip
  unzip_dir: artifacts/data_ingestion

